"""
Iterate over the examples of each of the data structures below. Predict the output generated by iterating over each data structure and calling print.

Lists
grade_lst = ['A', 'A', 'B', 'F']

Strings
word_to_spell = "dog"

Range Function (kind of a list)
range(1, 4)
"""

# List:
grade_lst = ['A', 'A', 'B', 'F']

for grade in grade_lst:
	print(grade)

# Output: A \n A \n B \n F \n

# String:
word_to_spell = "dog"
for char in word_to_spell:
	print(char)

# Output: d \n o\n g \n

# Range:
for num in range(1, 4):
	print(num)

# Output: 1 \n 2 \n 3 \n
