"""
Iterate over the examples of each of the data structures below. Predict the output generated by iterating over each data structure and calling print.

Lists
grade_lst = ['A', 'A', 'B', 'F']

Strings
word_to_spell = "dog"

Range Function (kind of a list)
range(1, 4)
"""

# List:
grade_lst = ['A', 'A', 'B', 'F']


# String:
word_to_spell = "dog"

# Range:
range(1, 4)